apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-spring-boot
spec:
  portal:
    capacity: 1
    expires: 60m
    orphaned: 5m
  workshops:
    - name: lab-spring-boot
    - name: lab-k8s-fundamentals
