#!/bin/bash

if ! [ -d ~/.sdkman ]; then
    curl get.sdkman.io | bash
    source ~/.sdkman/bin/sdkman-init.sh
fi

if ! [ -d ~/.sdkman/candidates/java/11.0.7-zulu ]; then
    sdk install java 11.0.7-zulu
fi
